### ISSUE TITLE
Issues with next version of ggplot2

### ISSUE THREAD

**Issue by thomasp85** [ShixiangWang/polar#2]
Hi

We preparing the next release of ggplot2 and our reverse dependency checks show that your package is failing with the new version. Looking into it we see that the issues are due to our switch to using the `linewidth` aesthetic for stroke width instead of `size`. Please see https://www.tidyverse.org/blog/2022/08/ggplot2-3-4-0-size-to-linewidth/ for more info on this.

Be aware that there is an additional issue with a warning about `'::' or ':::' import not declared from: ‘cli’` which is likely caused by ggpolar including code from ggplot2 at build time. See https://www.tidyverse.org/blog/2022/09/playing-on-the-same-team-as-your-dependecy/ for more info on this.

You can install the release candidate of ggplot2 using `devtools::install_github('tidyverse/ggplot2@v3.4.0-rc')` to test this out.

We plan to submit ggplot2 by the end of October and hope you can have a fix ready before then

Kind regards
Thomas

**Comment by ShixiangWang** [comment]
@thomasp85 Hi, thanks for your reminder. I will take a look and fix it ASAP.

**Comment by ShixiangWang** [comment]
A newer version is submitted to CRAN

**Comment by ShixiangWang** [comment]
@thomasp85 Free to reopen if the issue still exists :).
